---
- name: Generate config
  hosts: localhost
  tasks:
    - name: "Add all ip addresses"
      vars:
        hostnames: ""
      set_fact:
        hostnames: "{{ hostnames }} --hostname {{ item }}"
      loop: "{{ groups['all'] }}"

    - name: "Generate config"
      shell: |
        tendermint testnet --v {{ play_hosts | length }} --o /tmp/configs --config /tmp/config-template.toml --populate-persistent-peers {{ hostnames }}

- name: Converge validator node
  hosts: "*prod*"
  become: true
  gather_facts: smart
  vars:
    bc_polkadot_comp_state_prod: present
    bc_polkadot_comp_state_bench: present
    install_promstack: true
    bc_polkadot_extra_validator_id: "{{ play_hosts.index(inventory_hostname) | int }}"
    bc_polkadot_bench_shard_id: "{{ play_hosts.index(inventory_hostname) | int }}"
    bc_polkadot_bench_shards: "{{ play_hosts | length }}"
  roles:
    - role: tank.blockchain
  tasks:
    - name: "Show bc_polkadot_extra_validator_id"
      tags:
        - update
      debug:
        msg: "{{ bc_polkadot_extra_validator_id }}"
    - debug: msg="Validator instance(s) ready"
      tags: [print_action]
    - set_fact:
        bench_present: false
