---
- name: Generate config files
  hosts: localhost
  tasks:
    - name: "Generate files using tendermint"
      shell: |
        docker run --rm -v /tmp/tender:/tmp/config tendermint/tendermint testnet \
        --v 2 --o /tmp/config --populate-persistent-peers --hostname monach1 --hostname monach2

- name: Converge validator node
  hosts: "*prod*"
  become: true
  gather_facts: smart
  vars:
    bc_polkadot_comp_state_prod: present
    bc_polkadot_comp_state_bench: present
    install_promstack: true
    bc_polkadot_extra_validator_id: "{{ play_hosts.index(inventory_hostname) | int }}"
    bc_polkadot_bench_shard_id: "{{ play_hosts.index(inventory_hostname) | int }}"
    bc_polkadot_bench_shards: "{{ play_hosts | length }}"
  roles:
    - role: tank.blockchain
  tasks:
    - name: "Show bc_polkadot_extra_validator_id"
      tags:
        - update
      debug:
        msg: "{{ bc_polkadot_extra_validator_id }}"
    - debug: msg="Validator instance(s) ready"
      tags: [print_action]
    - set_fact:
        bench_present: true
