---
- name: Converge validator node
  hosts: "*prod*"
  become: true
  gather_facts: smart
  vars:
    bc_tendermint_comp_state_prod: present
    bc_tendermint_comp_state_bench: absent
    install_promstack: true
    bc_tendermint_extra_validator_id: "{{ play_hosts.index(inventory_hostname) | int }}"
    bc_tendermint_bench_shard_id: "{{ play_hosts.index(inventory_hostname) | int }}"
    bc_tendermint_bench_shards: "{{ play_hosts | length }}"
  roles:
    - role: tank.blockchain
  tasks:
    - name: "Show bc_tendermint_extra_validator_id"
      tags:
        - update
      debug:
        msg: "{{ bc_tendermint_extra_validator_id }}"
    - debug: msg="Validator instance(s) ready"
      tags: [print_action]
    - set_fact:
        bench_present: false
