---

- name: "Add all ip addresses"
  vars:
    hostnames: ""
  set_fact:
    hostnames: "{{ hostnames }} --hostname {{ item }}"
  loop: "{{ groups['bcpeers'] }}"
  delegate_to: localhost

- name: "Generate config"
  run_once: true
  shell: tendermint testnet --v {{ groups['bcpeers'] | length }} --o /tmp/configs --config /tmp/config-template.toml --populate-persistent-peers --log_level "main:info,state:info,*:error" {{ hostnames }}
  delegate_to: localhost

- name: "Set localhost config dir permissions to 0777"
  run_once: true
  shell: chmod -R 777 /tmp/configs
  delegate_to: localhost
  become: true

- name: Copy config and start nodes
  copy:
    src: /tmp/configs/node{{ play_hosts.index(inventory_hostname) | int }}
    dest: /opt/config
    mode: 0644

- name: "Set config dir permissions to 0777"
  shell: chmod -R 777 /opt/config/node{{ play_hosts.index(inventory_hostname) | int }}

- name: "Install docker python module"
  pip:
    name: docker

- name: "Start tendermint container"
  docker_container:
    name: "{{ bc_name }}_{{ bc_component_name }}"
    image: "{{ bc_tendermint_image }}"
    command: node --proxy_app kvstore
    network_mode: host
    volumes:
      - "/opt/config:/config"
    exposed_ports:
      - 26656
      - 26657
      - 26660
    ports:
      - "26656:26656"
      - "26657:26657"
      - "26660:26660"
    env:
      TMHOME: /config/node{{ play_hosts.index(inventory_hostname) | int }}
    stop_timeout: 600
    pull: true

- name: List data about prod container
  debug:
    var="{{ bc_name }}_{{ bc_component_name }}"
  tags:
    - never
    - debug
